// Error handling in JavaScript
// 1. try...catch
// 2. throw
// 3. finally

try{
    console.log('I am line 1');
} catch(error){
    console.log('I am catch block and error is: ', error);
} finally{
    console.log('I am finally block');
}